version: '3.9'

services:
  endava.hl7.fhir.openapi:
    image: endavahl7fhiropenapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Endava.Hl7.Fhir.OpenAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\alper\source\repos\Endava.Hl7.Fhir.OpenAPI.Demo\src\Endava.Hl7.Fhir.OpenAPI:/app
      - C:\Users\alper\source\repos\Endava.Hl7.Fhir.OpenAPI.Demo:/src
      - C:\Users\alper\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\alper\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/Endava.Hl7.Fhir.OpenAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true